## Import Semua Packages/Library yang Digunakan

In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## Data Wrangling

### Gathering Data

In [28]:
df = pd.read_csv("dataKaggle.csv")
df.head()

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,EMP0001,32,Non-binary,HR,Healthcare,13,Hybrid,47,7,2,Medium,Depression,No,Decrease,1,Unsatisfied,1,Weekly,Good,Europe
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,52,4,1,Medium,Anxiety,No,Increase,3,Satisfied,2,Weekly,Good,Asia
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,46,11,5,Medium,Anxiety,No,No Change,4,Unsatisfied,5,NaN,Poor,North America
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,32,8,4,High,Depression,Yes,Increase,3,Unsatisfied,3,NaN,Poor,Europe
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,35,12,2,High,NaN,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America

### Assessing Data

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Employee_ID                        5000 non-null   object
 1   Age                                5000 non-null   int64
 2   Gender                             5000 non-null   object
 3   Job_Role                           5000 non-null   object
 4   Industry                           5000 non-null   object
 5   Years_of_Experience                5000 non-null   int64
 6   Work_Location                      5000 non-null   object
 7   Hours_Worked_Per_Week              5000 non-null   int64
 8   Number_of_Virtual_Meetings         5000 non-null   int64
 9   Work_Life_Balance_Rating           5000 non-null   int64
 10  Stress_Level                       5000 non-null   object
 11  Mental_Health_Condition            3804 non-null   object
 12  Access_to_Mental_Health_Resources  5000 non-null   object
 13  Productivity_Change                5000 non-null   object
 14  Social_Isolation_Rating            5000 non-null   int64
 15  Satisfaction_with_Remote_Work      5000 non-null   object
 16  Company_Support_for_Remote_Work    5000 non-null   int64
 17  Physical_Activity                  3371 non-null   object
 18  Sleep_Quality                      5000 non-null   object
 19  Region                             5000 non-null   object
dtypes: int64(7), object(13)
memory usage: 781.4+ KB

In [30]:
df.isna().sum()

Employee_ID                             0
Age                                     0
Gender                                  0
Job_Role                                0
Industry                                0
Years_of_Experience                     0
Work_Location                           0
Hours_Worked_Per_Week                   0
Number_of_Virtual_Meetings              0
Work_Life_Balance_Rating                0
Stress_Level                            0
Mental_Health_Condition              1196
Access_to_Mental_Health_Resources       0
Productivity_Change                     0
Social_Isolation_Rating                 0
Satisfaction_with_Remote_Work           0
Company_Support_for_Remote_Work         0
Physical_Activity                    1629
Sleep_Quality                           0
Region                                  0
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.describe()

,Age,Years_of_Experience,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Social_Isolation_Rating,Company_Support_for_Remote_Work
count,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00
mean,40.99,17.81,39.61,7.56,2.98,2.99,3.01
std,11.30,10.02,11.86,4.64,1.41,1.39,1.40
min,22.00,1.00,20.00,0.00,1.00,1.00,1.00
25%,31.00,9.00,29.00,4.00,2.00,2.00,2.00
50%,41.00,18.00,40.00,8.00,3.00,3.00,3.00
75%,51.00,26.00,50.00,12.00,4.00,4.00,4.00
max,60.00,35.00,60.00,15.00,5.00,5.00,5.00

### Cleaning Data

In [33]:
# hapus baris duplikat
df = df.drop_duplicates()
print(f"Jumlah baris duplikat: {df.duplicated().sum()}")

Jumlah baris duplikat: 0

In [34]:
# standardisasi Employee_ID
# Ubah semua ke huruf KAPITAL & strip spasi; "nan" string -> NaN asli
df["Employee_ID"] = (
    df["Employee_ID"].astype(str).str.strip().str.upper().replace("NAN", np.nan)
)
print(df["Employee_ID"])

0       EMP0001
1       EMP0002
2       EMP0003
3       EMP0004
4       EMP0005
         ...
4995    EMP4996
4996    EMP4997
4997    EMP4998
4998    EMP4999
4999    EMP5000
Name: Employee_ID, Length: 5000, dtype: object

In [35]:
# standarisasi Gender
gender_map = {
    "male": "Male",
    "female": "Female",
    "non-binary": "Non-binary",
    "prefer not to say": "Prefer not to say",
}
df["Gender"] = df["Gender"].str.strip().str.lower().map(gender_map)
print(df["Gender"])

0       Non-binary
1           Female
2       Non-binary
3             Male
4             Male
           ...
4995          Male
4996        Female
4997        Female
4998        Female
4999          Male
Name: Gender, Length: 5000, dtype: object

In [36]:
# standarisasi Work_Location
loc_map = {
    "remote": "Remote",
    "onsite": "Onsite",
    "hybrid": "Hybrid",
}
df["Work_Location"] = df["Work_Location"].str.strip().str.lower().map(loc_map)
print(df["Work_Location"])

0       Hybrid
1       Remote
2       Hybrid
3       Onsite
4       Onsite
         ...
4995    Onsite
4996    Onsite
4997    Hybrid
4998    Remote
4999    Onsite
Name: Work_Location, Length: 5000, dtype: object

In [37]:
# standarisasi Stress_Level
stress_map = {
    "low": "Low",
    "medium": "Medium",
    "high": "High",
}
df["Stress_Level"] = df["Stress_Level"].str.strip().str.lower().map(stress_map)
print(df["Stress_Level"])

0       Medium
1       Medium
2       Medium
3         High
4         High
         ...
4995      High
4996       Low
4997      High
4998       Low
4999       Low
Name: Stress_Level, Length: 5000, dtype: object

In [38]:
# standarisasi Access_to_Mental_Health_Resources
mhr_map = {
    "yes": "Yes",
    "no": "No",
}
df["Access_to_Mental_Health_Resources"] = (
    df["Access_to_Mental_Health_Resources"].str.strip().str.lower().map(mhr_map)
)
print(df["Access_to_Mental_Health_Resources"])

0        No
1        No
2        No
3       Yes
4       Yes
       ...
4995    Yes
4996    Yes
4997     No
4998    Yes
4999    Yes
Name: Access_to_Mental_Health_Resources, Length: 5000, dtype: object

In [39]:
# standarisasi Productivity_Change
prod_map = {
    "increase": "Increase",
    "decrease": "Decrease",
    "no change": "No Change",
}
df["Productivity_Change"] = (
    df["Productivity_Change"].str.strip().str.lower().map(prod_map)
)
print(df["Productivity_Change"])

0        Decrease
1        Increase
2       No Change
3        Increase
4        Decrease
          ...
4995     Decrease
4996     Decrease
4997     Increase
4998     Increase
4999    No Change
Name: Productivity_Change, Length: 5000, dtype: object

In [40]:
# standarisasi Satisfaction_with_Remote_Work
sat_map = {
    "satisfied": "Satisfied",
    "unsatisfied": "Unsatisfied",
    "neutral": "Neutral",
}
df["Satisfaction_with_Remote_Work"] = (
    df["Satisfaction_with_Remote_Work"].str.strip().str.lower().map(sat_map)
)
print(df["Satisfaction_with_Remote_Work"])

0       Unsatisfied
1         Satisfied
2       Unsatisfied
3       Unsatisfied
4       Unsatisfied
           ...
4995        Neutral
4996      Satisfied
4997      Satisfied
4998    Unsatisfied
4999    Unsatisfied
Name: Satisfaction_with_Remote_Work, Length: 5000, dtype: object

In [41]:
# standarisasi Physical_Activity
# NaN -> isi dengan modus
phys_map = {
    "daily": "Daily",
    "weekly": "Weekly",
}
df["Physical_Activity"] = df["Physical_Activity"].str.strip().str.lower().map(phys_map)
mode_physical = df["Physical_Activity"].mode()[0]
df["Physical_Activity"] = df["Physical_Activity"].fillna(mode_physical)
print(f"Modus Physical_Activity: {mode_physical}")
print(df["Physical_Activity"])

Modus Physical_Activity: Weekly
0       Weekly
1       Weekly
2       Weekly
3       Weekly
4       Weekly
         ...
4995    Weekly
4996    Weekly
4997     Daily
4998     Daily
4999    Weekly
Name: Physical_Activity, Length: 5000, dtype: object

In [42]:
# standarisasi Sleep_Quality
sleep_map = {
    "good": "Good",
    "average": "Average",
    "poor": "Poor",
}
df["Sleep_Quality"] = df["Sleep_Quality"].str.strip().str.lower().map(sleep_map)
print(df["Sleep_Quality"])

0          Good
1          Good
2          Poor
3          Poor
4       Average
         ...
4995    Average
4996    Average
4997       Poor
4998    Average
4999       Poor
Name: Sleep_Quality, Length: 5000, dtype: object

In [43]:
# standarisasi Mental_Health_Condition
# NaN berarti tidak ada kondisi yang teridentifikasi -> isi dengan 'None'
df["Mental_Health_Condition"] = df["Mental_Health_Condition"].fillna("None")
print(df["Mental_Health_Condition"])

0       Depression
1          Anxiety
2          Anxiety
3       Depression
4             None
           ...
4995       Burnout
4996    Depression
4997       Burnout
4998          None
4999    Depression
Name: Mental_Health_Condition, Length: 5000, dtype: object

In [44]:
# standarisasi kolom numerik dan menghapus outlier
num_cols = [
    "Age",
    "Years_of_Experience",
    "Hours_Worked_Per_Week",
    "Number_of_Virtual_Meetings",
    "Work_Life_Balance_Rating",
    "Social_Isolation_Rating",
    "Company_Support_for_Remote_Work",
]
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Batas nilai wajar berdasarkan domain knowledge
bounds = {
    "Age": (18, 70),
    "Years_of_Experience": (0, 50),
    "Hours_Worked_Per_Week": (0, 80),
    "Number_of_Virtual_Meetings": (0, 30),
    "Work_Life_Balance_Rating": (1, 5),
    "Social_Isolation_Rating": (1, 5),
    "Company_Support_for_Remote_Work": (1, 5),
}

total_outliers = 0
for col, (lo, hi) in bounds.items():
    mask = (df[col] < lo) | (df[col] > hi)
    total_outliers += mask.sum()
    df[col] = df[col].where(~mask)  # nilai di luar batas -> NaN

In [45]:
df.to_csv("dataKaggle_clean.csv", index=False)
print(f"Data bersih tersimpan. Shape akhir: {df.shape}")

Data bersih tersimpan. Shape akhir: (5000, 20)